### ISSUE TITLE
The last block is not decompressed when frame check sum is null.

### ISSUE THREAD

**Issue by funcodeio** [Cyan4973/lz4#106]
Hello guys, 

I recently found out a bug regarding decompressing a file which does not have frame-crc.
If I decompress the file without frame crc, the last block is not decompressed, and is ignored.

Here is a simple example, 
```
>echo "Hello World" | ./lz4 -c | ./lz4 -d -c --no-sparse
Hello World
```
```
>echo "Hello World" | ./lz4 -c --no-frame-crc | ./lz4 -d -c --no-sparse
(nothing is printed)
```

I looked into the problem. 
And, I found out that LZ4F_decompress behaves differently depending on whether there is frame-crc or not. If there is the crc, LZ4F_decompress returns "4" after reading the last block. However, if there is not the crc, LZ4F_decompress returns "0" after reading the last block. This makes LZ4IO_decompressLZ4F return earlier before writing last block into the output file.

I think there are two solutions.

1. 
Making LZ4F_decompress behave the same way regardless of whether there is crc or not. 
This is, making it return "4" even if there is not frame crc.

2. 
Switching the order of if-statement in LZ4IO_decompressLZ4F in lz4io.c like this.
```
diff --git a/programs/lz4io.c b/programs/lz4io.c
index 209f5ed..bfa3488 100644
--- a/programs/lz4io.c
+++ b/programs/lz4io.c
@@ -844,7 +844,6 @@ static unsigned long long LZ4IO_decompressLZ4F(dRess_t ress, FILE* srcFile, FILE
             nextToLoad = LZ4F_decompress(ress.dCtx, ress.dstBuffer, &decodedBytes, (char*)(ress.srcBuffer)+pos, &remaining, NULL);
             if (LZ4F_isError(nextToLoad)) EXM_THROW(66, "Decompression error : %s", LZ4F_getErrorName(nextToLoad));
             pos += remaining;
-            if (!nextToLoad) break;
 
             if (decodedBytes)
             {
@@ -853,6 +852,8 @@ static unsigned long long LZ4IO_decompressLZ4F(dRess_t ress, FILE* srcFile, FILE
                 DISPLAYUPDATE(2, "\rDecompressed : %u MB  ", (unsigned)(filesize>>20));
                 storedSkips = LZ4IO_fwriteSparse(dstFile, ress.dstBuffer, decodedBytes, storedSkips);
             }
+
+            if (!nextToLoad) break;
         }
     }
 ```

Best regards, 
Yongwoon Cho

**Comment by Cyan4973** [comment]
Hi Yongwoon

You are totally right.
This LZ4IO test must be modified as you suggest.

The test suite must also be updated to verify and catch such issue.

Both modifications have been integrated into latest "dev" branch update : 26065c3f47381c6ebe56ea114015b3c2b1c2a615

**Comment by funcodeio** [comment]
Thanks for the quick fix!!
