### ISSUE TITLE
lz4.vim

### ISSUE THREAD

**Issue by funcodeio** [Cyan4973/lz4#120]
Hello,

I recently made [lz4.vim], just a simple vim plugin to read and write lz4frame files. It shows the original content of a compressed file, and enables you to modify the content.  
[lz4.vim]: https://github.com/funcodeio/lz4.vim

If there are vim users, can you try it and give some feedback to me? 
Here is the repository.

https://github.com/funcodeio/lz4.vim

Thank you!

**Comment by Cyan4973** [comment]
That's a really good idea.
Would you like your work linked from lz4 homepage ?

**Comment by funcodeio** [comment]
Yes, please. I would appreciate it if you do that. 
Also, it will help people playing with lz4 frame.

**Comment by Cyan4973** [comment]
done
http://lz4.org

**Comment by Cyan4973** [comment]
Also, maybe it could be a good idea to introduce your plugin on the lz4 public group, at
https://groups.google.com/forum/#!forum/lz4c
