### ISSUE TITLE
xxHash namespace issue with lz4 library

### ISSUE THREAD

**Issue by Cyan4973** [Cyan4973/lz4#125]
Since a few revisions, lz4 library now integrates lz4frame,
which needs xxHash for checksum validation.
xxHash is therefore integrated into lz4 library, but not exposed (no *.h is provided), since it's for internal library use only.

The problem is, from an ABI perspective, xxHash functions are nonetheless there.
So when someone try to link lz4 library on top of their own xxHash library, it conflicts, since C has no namespace separation.

This use case should be better supported.

Ideally, there would be a way to create lz4 library with its own private version of xxHash library, which would remain invisible outside of lz4 library.

**Comment by Cyan4973** [comment]
One potential solution : define some kind of prefix, which would make xxHash function calls differently named (sort of namespace emulation). It seems `zconf.h` from zlib is able to do that.

**Comment by Cyan4973** [comment]
Done into latest update

**Comment by mitchblank** [comment]
I just got bit by something related to this as well.  I use both xxhash on its own and lz4, so I'd previously been compiling xxhash myself and then just tweaking lz4 to build against that.  After all, no reason to have two copies of the xxhash code taking up space in the icache!

Recent versions of xxhash break this pattern, though:

```
lz4-r131/lib/lz4frame.c:125:19: error: field ‘xxh’ has incomplete type
     XXH32_state_t xxh;
                   ^
lz4-r131/lib/lz4frame.c:148:19: error: field ‘xxh’ has incomplete type
     XXH32_state_t xxh;
                   ^
```

It's unfortunate that doesn't work any more, and two separate copies of xxhash are now apparently required?

**Comment by Cyan4973** [comment]
ah, sorry,
lz4 r131 was published before xxHash v0.5, so it's not adapted to this new interface.

There are a few possibilities : 
- Have lz4 include its own version of xxHash (current design by default)
- use xxHash r42, which is compatible with direct declaration
- patch lz4 to use xxHash v0.5 (dev branch)

The 3rd solution will be employed for next update of lz4.
But no date set, as [zstd](http://www.zstd.net) is current top priority.

**Comment by mitchblank** [comment]
OK, understood.  Thanks for the fast reply.  What I've done currently is to just patch lib/lz4frame.c, i.e.

```
-    XXH32_state_t xxh;
+    XXH32_stateBody_t xxh;
```

...and then added a bunch of casts like:

```
XXH32_reset((XXH32_state_t *) &(cctxPtr->xxh), 0);
```

I think that should probably be fine although probably not strictly wrt strict aliasing.  I'm not using LTO though so the fact that we're passing the pointer across a translation-unit boundary should make it fairly safe.

It might be good for newer versions of gcc/clang if you add `__attribute__((may_alias))` to the `XXH32_stateBody_t`/`XXH64_stateBody_t` type definitions?  Not sure if it will be a difference or not.

**Comment by Cyan4973** [comment]
> I think that should probably be fine although probably not strictly wrt strict aliasing

wrt strict aliasing, it is fine because we don't access the memory segment from 2 different definitions : only the `XXH32_state_t*` pointer will ever be used to read and write.

Now, some compilers might be over-cautious and just flag that as a warning _just in case_ it could become a strict aliasing issue, for reasons they don't even try to analyze. This is a false positive, but still a problem for build systems with such warning enforced by default and zero warning tolerance policy.

In which case, using an intermediate `void*` pointer just to confuse the warning heuristic would do the trick. It's always a pity to have to fight the compiler like this, but that can nonetheless be better (ie more accurate) than disabling the warning altogether....

> It might be good for newer versions of gcc/clang if you add `__attribute__((may_alias))`

It's a good suggestion. Though it's compiler-specific, which is something I try to avoid whenever possible, for portability. That's still considerably better than risking a bug.

Though as stated before, it shouldn't be a problem as long as the pointer to access data is always the same (ie never directly access / modify `XXH32_stateBody_t` ).

**Comment by mitchblank** [comment]
The release of zstd seems to have made this even more complicated... based on the git comments it claims that lib/common/xxhash.c is xxHash 0.6.2 with only minor tweaks, but the code seems to have diverged quite a bit.

From looking at the diff it mostly seems that the functions are mostly the same but the copy that lives inside zstd has a lot of them in a different order.

I'm guessing that if you want to share a single copy of this code between lz4, zstd, and direct xxhash users the best strategy is to start with the version currently in zstd, since it seems to have the most recent changes?  Or are there subtle differences in the hash function itself that make such sharing impossible?

**Comment by Cyan4973** [comment]
xxHash version of zstd is supposed to be in sync with xxHash repo itself.

LZ4 is not synchronized though, since it's a bit older.
It will need to be updated.

**Comment by mitchblank** [comment]
> xxHash version of zstd is supposed to be in sync with xxHash repo itself.

I'm not sure if I follow.  It's certainly not textually synced right now, at least at the tip of develop in each project:

```
$ for ext in .h .c; do diff -u xxHash/xxhash$ext zstd/lib/common/xxhash$ext; done | diffstat
 xxhash.c |  507 ++++++++++++++++++++++++++++++---------------------------------
 xxhash.h |  130 ++++++++--------
 2 files changed, 311 insertions(+), 326 deletions(-)
```

It doesn't look like any substantive changes to me, but a lot of code is rearranged, comments reworded etc.  If they were synced I would expect the only difference to be the `#  define XXH_NAMESPACE ZSTD_` in the zstd copy.

> Note that changes never affect the hash formula, which remains identical in all circumstances.

Thank you for verifying that.  I had assumed that would be the case but I didn't want to break something just in case zstd was using its own "dialect" of the algorithm or something.

With some minor makefile tweaks I have lz4 and zstd sharing a single copy of xxhash.  I'm sure in the end it doesn't matter at all, but I just hate wasting I-Cache :)
