### ISSUE TITLE
Option for comression level with tar

### ISSUE THREAD

**Issue by szepeviktor** [Cyan4973/lz4#135]
lz4 could be used as a tar compression program: it understands `-d`
May I set compression level with something like `GZIP_OPT` in gzip?
```
LZ4_OPT=-9 tar -I /usr/bin/lz4 "$@"
```

**Comment by Cyan4973** [comment]
That's a very good point Viktor.

This option doesn't exist yet, but I feel it could be a good idea to integrate it for a future release.

**Comment by t-mat** [comment]
I don't oppose to this suggestion itself, but it seems this feature has been deprecated in recent version:

 - [gzip/NEWS](http://git.savannah.gnu.org/cgit/gzip.git/tree/NEWS?id=5054e88a7934d5ff5ec14231c8b8676161bb45fa#n5)
> ** Changes in behavior
> 
>   The GZIP environment variable is now obsolescent; gzip now warns if
>   it is used, and rejects attempts to use dangerous options or operands.
>   You can use an alias or script instead.

 - warning message in gzip.c
   - [warning: GZIP environment variable is deprecated; use an alias or script](http://git.savannah.gnu.org/cgit/gzip.git/tree/gzip.c?id=5054e88a7934d5ff5ec14231c8b8676161bb45fa#n479)
 - OPTIONS_VAR in tailor.h
   - ["GZIP"](http://git.savannah.gnu.org/cgit/gzip.git/tree/tailor.h?id=5054e88a7934d5ff5ec14231c8b8676161bb45fa#n241)
   - ["GZIP_OPT" for VMS](http://git.savannah.gnu.org/cgit/gzip.git/tree/tailor.h?id=5054e88a7934d5ff5ec14231c8b8676161bb45fa#n153)

**Comment by Cyan4973** [comment]
Good catch @t-mat 

Maybe we should think twice before implementing such a feature. Maybe it was considered a security issue, notably if the variable could contain multiple complex commands.

**Comment by t-mat** [comment]
Here is a discussion thread in bug-gzip archives.

 - [bug#20104: [PATCH] gzip: make the GZIP env var obsolescent](http://lists.gnu.org/archive/html/bug-gzip/2015-03/msg00001.html)

**Comment by Cyan4973** [comment]
yeah, so indeed, the variable can be used as a way to script some unwanted actions.
Given that security issues have become way more important these days, I believe we'll select the cautious route ...

**Comment by Cyan4973** [comment]
We'll close it for now, since it seems to expose to security concerns.

**Comment by szepeviktor** [comment]
OK.
