### ISSUE TITLE
Decompressing skipping some bytes in output

### ISSUE THREAD

**Issue by dosomder** [Cyan4973/lz4#140]
Sony uses for their android firmwares ext4 images which are LZ4 compressed. I am trying to create an application for arm (based on C) to decompress those images on a device directly using your library.
I have a similiar application for Windows based on C# (using lz4net).

The input file is ~2GB and the output file ~5GB. However my arm app can not correctly decompress the image. For my tests I fill the output file with 00 before decompressing it and after running my app, some bytes still remain 00. The locations are random and *change with every execution*. At some location it's just one byte in the middle of the decompressed block which is still 00.
![lz4problem2](https://cloud.githubusercontent.com/assets/3040570/9289681/3285a8ba-4379-11e5-8669-7f4d26c96a98.png)

But sometimes a few bytes are wrong followed by 00 until the next page (?). (Note that this is basically in the **middle of the block**.)
![lz4problem](https://cloud.githubusercontent.com/assets/3040570/9289685/4e216c44-4379-11e5-9b66-a77b67ef9280.png)

I have tried LZ4_decompress_fast
```
if(LZ4_decompress_fast(source, dest, decompressedsize) != compressedsize)
		perror("Error decompressing LZ4 block");
```
and also LZ4_decompress_safe
```
if(LZ4_decompress_safe(source, dest, compressedsize, decompressedsize) != decompressedsize)
		perror("Error decompressing LZ4 block");
```

I have tried gcc-4.8, gcc-4.9 and clang3.6 (those provided within the Android NDK). Tried various optimization flags from -O0, -O2, -O3, -Os but the issue remains and I don't get any error during decompression.

My C# app and also some other app (which uses the Java implementation of LZ4) can decompress the image correctly.

I can't reproduce the problem if I try to decompress a single block which occured to be faulty once.

Do you have any idea how to fix this problem?

**Comment by dosomder** [comment]
By the way I also compiled it for x86 and run it on a Ubuntu Virtual machine. It decompressed without any problems.

**Comment by Cyan4973** [comment]
It's fairly difficult to tell, without access to test data nor test suite.
A few comments out of my mind : 

> The input file is ~2GB and the output file ~5GB

That's way too much for a single call to `LZ4_decompress()`. Data must be cut into blocks, and some metadata to manage these blocks is necessary. Knowing how these blocks are generated (_frame format_) is required to push investigation forward.

Given the nature of the pb, should nothing be found on the software side, maybe the hardware side could be investigated too. Does this problem happen on a single hardware machine, or do you have multiple equivalent ones (arm based) to confirm the issue ?

**Comment by dosomder** [comment]
I understand it's difficult, to me it's also confusing. Please let me elaborate a few things

> The input file is ~2GB and the output file ~5GB

The input file is of course cut into many smaller blocks. As I said, decompression works fine on Windows / Linux x86, the problem is when I try to decompress the same file on my phone (arm).

I will try to get another phone to run it there. I'll also try to add some logging to `LZ4_decompress_generic` to maybe get a better understanding of what is happening if this anomaly occurs.

**Comment by dosomder** [comment]
So I tested it now on a Samsung Galaxy Tab S 10.5 (SM-T805). The result: The output file was **correct**!

Could it be that the cpu of my other device is misinterpreting some command and generates wrong result?

Here is the output of /proc/cpuinfo

**Galaxy Tab S (working)**
```
Processor       : ARMv7 Processor rev 3 (v7l)
processor       : 0
BogoMIPS        : 1590.88

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 3

Hardware        : Samsung EXYNOS5420
Revision        : 0007
Serial          : 0436xxxxxxxxxxxx
```

**Sony Xperia Z3 Compact (not working)**
```
Processor       : ARMv7 Processor rev 1 (v7l)
processor       : 0
BogoMIPS        : 38.40

processor       : 1
BogoMIPS        : 38.40

processor       : 2
BogoMIPS        : 38.40

processor       : 3
BogoMIPS        : 38.40

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x51
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x06f
CPU revision    : 1

Hardware        : Qualcomm MSM8974PRO-AC
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by Cyan4973** [comment]
Misinterpreting assembly commands is very unlikely.

What could happen is that the RAM of the faulty system is starting to fail.
Such effect could be triggered partly because of the high speed of the decompression process.
( Similar to [row hammering](https://en.wikipedia.org/wiki/Row_hammer) ) .

Of course here we are not hammering anything, so it should not happen. It would take a weak RAM, which leak resistance is starting wear off, for such effect to become perceptible.

Another possible culprit could be the compiler, generating buggy code.
Try to compiling at -O2 rather than -O3. The resulting binary should run slower, and would likely work better.

**Comment by dosomder** [comment]
I already tried with all the different optimization flags (see first post). Also if the compiler would indeed create buggy code, why would it work on another device?

**Comment by Cyan4973** [comment]
> if the compiler would indeed create buggy code, why would it work on another device?

It could be because they are different versions, and/or because the precise target architecture is slightly different.

Anyway, this is only one possible outcome. The possibility of a hardware failure is also likely in your case, since the issue is specific to a single device.

**Comment by dosomder** [comment]
So I added a hash check after decompressing. It seems right after decompressing the hashes are correct but the final output file is wrong. So something must be tampering the memory until `munmap` is called. Probably not an issue of your library though. Sorry for bothering you :)
