### ISSUE TITLE
cp -a not available on all platforms

### ISSUE THREAD

**Issue by jens-gpio** [Cyan4973/lz4#147]
In lib/Makefile, the -a switch is used for cp. As I do not know what -a does and it's not available for my platform, I'd like to request that cp -a is not used.
I'm hoping that you will consider using GNU autotools to generate the Makefile for the platform, which is being targeted; eg. so one could type ./configure && make && [sudo] make install

**Comment by Cyan4973** [comment]
according to `man cp` :
````
-a, --archive
              same as -dR --preserve=all
````

This section of the Makefile is a remnant of an old contribution by the Fedora team.  I suspect the `-a` was put there to make sure the `chmod` properties remain unmodified by the `cp` operation.

**Comment by Cyan4973** [comment]
Quick question : 
Does the `install` command work fine on your system ?
(it is used within `programs/Makefile` for example)

**Comment by jens-gpio** [comment]
> Does the install command work fine on your system ?

Nope, it fails; however when I remove -a, it does work, when I type 'sudo make install'.
My system is Mac OS X 10.5.8 ("Leopard"); the 'cp' command installed on this system is slightly different from the ones found on for instance Linux; installing a different cp is (of course) not recommended, as that would break existing maintenance scripts.

**Comment by jens-gpio** [comment]
From 'man cp':
"     -p    Cause cp to preserve the following attributes of each source file
           in the copy: modification time, access time, file flags, file mode,
           user ID, and group ID, as allowed by permissions.  Access Control
           Lists (ACLs) will also be preserved."

-a is unknown, -d is unknown, -R is recursive.

**Comment by Cyan4973** [comment]
> > Does the install command work fine on your system ?

> Nope, it fails; however when I remove -a, it does work, when I type 'sudo make install'.

Sorry, that wasn't the question.

If you type `sudo make install` from lz4 root src directory, it will call the `make install` of `lib` directory and `programs` directory. The `make install` of `programs` uses the `install` command.

The `install` command has nothing to do with the `Makefile` entry. It's more like the `cp` command, something that can be called from the command line. There is even a `man install` page available. In essence, it's almost like a `cp` followed by a `chmod`.

The point is, if `cp` can be different from system to system, maybe `install` behavior will be more stable.

Using `cp -p` is another potential fallback plan.

**Comment by jens-gpio** [comment]
Sorry; I wasn't very focused.
The install command exists, but it seem to have the same problems as the cp command.
Some of the switches differ; here are a few examples:
-C means 'Copy the file', on Linux -C is for comparing.
-d creates directories (on Linux this is -D)
-D does not exist.
-S is safe copy, on Linux this is "suffix".
-t and -T does not exist.
--double-dash switches do not exist; eg. --group, --mode, --preserve-timestamps, etc... do not exist.

-I do not know how automake does it, but automake works with all the systems I've been using.

**Comment by Cyan4973** [comment]
OK, sounds like a mess.

I'm surprised to not have received more bug reports from OS-X users, as it seems the installation process would be just broken for this platform.

> -d creates directories (on Linux this is -D)

Not on my Linux platform : 

````
-d, --directory
         treat all arguments as directory names; create all components of the specified directories

-D     create all leading components of DEST except the last, then copy SOURCE to DEST
````

This is important as the only options which matter for `lz4 install` are `-m` and `-d`.

Looks like it's going to be fun to only use the command switches which are safe across all, or at least most platforms...

**Comment by ldemailly** [comment]
On my mac with the current version (Yosemite 10.10.5)

cp does have:
     -a    Same as -pPR options. Preserves structure and attributes of files but not directory structure.

**Comment by jens-gpio** [comment]
@ldemailly ... I know, but that does not make the script compatible with all platforms (including mine); Leopard still does not support -a on cp. It's best to avoid using cp -a, because it's not safe.

**Comment by ldemailly** [comment]
@jens-gpio you are right, I guess -a shouldn't be necessary, regular cp + optional chmod / chown should be fine (I was just pointing out that recent Mac OS do have a more standard/recent BSD cp)

maybe we should use cmake (instead of autotools) to solve those :-)

**Comment by jens-gpio** [comment]
I don't mind if using cmake for fixing it. I must admit that I am not an expert on autotools myself. ;)
The -a problem may also be present on Sparc (that's just a guess, so I might be wrong) and older versions of UNIX.

**Comment by Cyan4973** [comment]
Got it.
The `cp -a` command was selected instead of `install` (which is preferred on almost all other lines in the install script) as a way to _copy a link while preserving it as a link_.

Other variations I've tried would copy the target of the link instead.

Let's try to find some work-around ...

**Comment by Cyan4973** [comment]
Couldn't find a way to copy the link while preserving it as a link without using command switches, hence having the risk of incompatibility described in this issue.

As a work-around, decided to recreate the link directly into the `lib` directory.

Test version available in the "dev" branch :  cd18ed3086a3eaf5d6531412959bd875b74dc6c1

**Comment by jens-gpio** [comment]
If it's simply a matter of handling symlinks in a certain way, it might be possible to use the 'find' command and then check each file. I don't like this solution myself though; I'm just thinking out loud. ;)
It's also possible to make a recursive function in a Makefile:


# Routine to traverse a directory and find all matching wildcards:
wildcards=$(wildcard $1$2) $(foreach p,$(wildcard $1*),$(call wildcards,$p/,$2))

-I like this better, but supporting both '/' and '\' might be tedious.
Here's how I use it from my Makefile, in order to find all sources:

CSRCS               = $(call wildcards,src$(slash),*.c)
CSRCS               += $(call mwildcards,*.c,$(EXTRA_SRC))
...etc...

**Comment by Cyan4973** [comment]
Could you test if the current version in the "dev" branch solves your issue regarding `make install` ?

Regards

**Comment by jens-gpio** [comment]
Yes, the current dev branch works for me. :)

**Comment by Cyan4973** [comment]
Solved into (future) r132 (currently : dev branch)
