### ISSUE TITLE
r131 reports wrong version if compiled with custom CFLAGS

### ISSUE THREAD

**Issue by mauritiusdadd** [Cyan4973/lz4#149]
#### Description

If the program is compiled using a custom CFLAGS, then lz4 reports the wrong release version:
```
$ lz4 --version
*** LZ4 command line interface 64-bits r128, by Yann Collet (Sep  1 2015) ***
```

#### How to reproduce

```
CFLAGS="-Wall" make
make install
lz4 --version
```

#### Analisys
The problem seems to be that the release version is set in [programs/Makefile](https://github.com/Cyan4973/lz4/blob/r131/programs/Makefile#L42) trough the variable CFLAGS:

```make
CFLAGS ?= -O3
CFLAGS += -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes -pedantic -DLZ4_VERSION=\"$(RELEASE)\"
FLAGS  := -I../lib $(CPPFLAGS) $(CFLAGS) $(LDFLAGS)
```
However, here make is invoked from the [main Makefile](https://github.com/Cyan4973/lz4/blob/r131/Makefile#L72) using the option <i>-e</i> which cause the variables inside the Makefile to be overridden by the environment variables. This means that <i>LZ4_VERSION</i> is never defined so the default release version is used. The latter is defined in [programs/lz4cli.c](https://github.com/Cyan4973/lz4/blob/master/programs/lz4cli.c#L89) but is still r128.

**Comment by mauritiusdadd** [comment]
This issue can be solved by moving the definition of <i>LZ4_VERSION</i> from <i>CFLAGS<i> directly to <i>FLAGS</i>. I also made a patch:

```diff
diff --git a/programs/Makefile b/programs/Makefile
index f422902..4506dcc 100644
--- a/programs/Makefile
+++ b/programs/Makefile
@@ -39,8 +39,8 @@ RELEASE?= r131
 DESTDIR?=
 PREFIX ?= /usr/local
 CFLAGS ?= -O3
-CFLAGS += -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes -pedantic -DLZ4_VERSION=\"$(RELEASE)\"
-FLAGS  := -I../lib $(CPPFLAGS) $(CFLAGS) $(LDFLAGS)
+CFLAGS += -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-qual -Wcast-align -Wstrict-prototypes -pedantic
+FLAGS  := -I../lib $(CPPFLAGS) $(CFLAGS) -DLZ4_VERSION=\"$(RELEASE)\" $(LDFLAGS)
 
 BINDIR := $(PREFIX)/bin
 MANDIR := $(PREFIX)/share/man/man1
diff --git a/programs/lz4cli.c b/programs/lz4cli.c
index cc5c96a..4bbbf88 100644
--- a/programs/lz4cli.c
+++ b/programs/lz4cli.c
@@ -87,7 +87,7 @@
 ******************************/
 #define COMPRESSOR_NAME "LZ4 command line interface"
 #ifndef LZ4_VERSION
-#  define LZ4_VERSION "r128"
+#  define LZ4_VERSION "r131"
 #endif
 #define AUTHOR "Yann Collet"
 #define WELCOME_MESSAGE "*** %s %i-bits %s, by %s (%s) ***\n", COMPRESSOR_NAME, (int)(sizeof(void*)*8), LZ4_VERSION, AUTHOR, __DATE__
```

**Comment by Cyan4973** [comment]
That's a good point.

Note that with r132, Makefile has been refactored, in a way which should prove compatible with your requirement.

r132 is an ongoing development version, available only in the "dev" branch for now.

On my station : 
````
CFLAGS="-Wall" make
make install
lz4 --version
*** LZ4 command line interface 64-bits r132, by Yann Collet (Sep  1 2015) ***
````

**Comment by mauritiusdadd** [comment]
Yeah, you're right... I haven't thought to test the code from the "dev" branch. I can confirm that the issues is solved in r132, thanks.

**Comment by Cyan4973** [comment]
solved into (future) r132
