### ISSUE TITLE
Reduce multiple 0xff in length encodings (suggestion)

### ISSUE THREAD

**Issue by jens-gpio** [Cyan4973/lz4#155]
I once wrote a small compression/decompression tool, which was RLE based.
While doing so, I found a lot of redundancy in current implementations and came up with making some values that had special meanings. This reduced the size of the compressed files dramatically.

One idea I never tried, was to use inverted MIDI bytes. Inverted, because there's an advantage in having values 0 ... 127 mean "more data bytes" and values 128 ... 255 "last data byte".

Imagine you have a length, which is 8387 bytes. For this, you'd need a 0x0f in the token and 32 runs of 0xff followed by the value 212.

Instead, I think it would pay to still have the 0x0f in the token, but the length section could be processed by the decoder like the following:
1: zero the length variable
2: shift the length variable left by 7
3: read a data byte
4: add the data byte to the length variable
5: If bit 7 of the data byte is zero, then go back to step 3
6: add 15-128 to the length (15 is the value from the token, -128 for zeroing the last data byte's bit 7)

Values from 15 to 142 will still only use a single data byte. Values from 143 to 16398 would use two bytes; values from 16399 to 2097166 would use three bytes; higher values are not very likely, but still they would not use a lot of space.
The only place I think the old system might be able to win, is with length values between 143 and 269 (eg. a single byte). If a compressed stream contains a lot of those, then my suggested method will cause the file to be larger.

A different approach could be to analyze the length values. If for instance the length '18' is used thousands of times, then it might be a good idea to tokenize it, thus values from 0 ... 251 would look up length values; a value of 252 would mean "add a new byte sized value", a value of 253 would mean "add new 16-bit sized value", etc...

**Comment by Cyan4973** [comment]
Alternate length counter have been proposed a number of times.
(See related notes from Charles Bloom, on lznib and optimal length encoding, for example : http://cbloomrants.blogspot.fr/2012/09/09-04-12-encoding-values-in-bytes-part-4.html)
The one you propose is pretty good.

Lz4 format was designed early, as a way to learn compression. Therefore, the format was made as simple as possible, to reduce the complexity on that part. Should I had more experience, I would probably have tried something similar to your idea.

In the end, the simple choice proved to be a blessing : 
"good" alternative length counter tend to compress better, but the final net gain also tend to be small, if not negligible (except obviously on pathological data created to show off alternate length counter strength).

But the small benefit comes at some cost, complexity and speed. And both tend to be overpriced im ny view with regards to the small benefits.

At the end of the day, what prevents me from implementing such ideas into lz4 is the existing ecosystem : I can't promote a different format which would break compatibility with existing one, all this for the benefit of some small gains.

Improvement must be way more impressive to be worth the hassle. Hence [zstd](https://github.com/Cyan4973/zstd).

**Comment by jens-gpio** [comment]
I agree on that the 0xff runs is actually not too bad a choice, because the length will only use 1/256 of the data space in the compressed file; this means it is not a painful overhead.
With LZ4, you've added another proof that "simple is good" is a truth.
-And I completely follow you on not changing the existing format.
...But feel free to use one of the ideas in case you create a different compression algorithm. ;)

**Comment by Cyan4973** [comment]
Sure ! ;-)
