### ISSUE TITLE
feature request: allowing compression into fixed-size blocks

### ISSUE THREAD

**Issue by dankimmel** [Cyan4973/lz4#163]
Today we can compress/decompress incrementally from a stream of fixed size input blocks into one contiguous output block, but we can't do compression into a stream of fixed size *output* blocks. This is useful for times when you will compress the data and then immediately hand it to something that needs a scatter/gather list as input, such as a network or block device driver.

**Comment by Cyan4973** [comment]
Actually, this functionality exists.
Look at `int LZ4_compress_destSize()` definition.

**Comment by dankimmel** [comment]
I completely missed that! I think I didn't recognize it as what I was looking for because I was expecting it to take an `LZ4_stream_t` similar to `LZ4_compress_fast_continue`. Anyway, thanks for the quick turnaround!
