### ISSUE TITLE
no configure file to build with?

### ISSUE THREAD

**Issue by asdfljdasflkjwfd** [Cyan4973/lz4#176]
$ make install       
make[1]: Entering directory `/home/username/src/lz4-r131/lib'
compiling static library
compiling dynamic library 1.7.1
creating versioned links
install: cannot change permissions of `/usr/local/lib/pkgconfig/': No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/username/src/lz4-r131/lib'
make: *** [install] Error 2

How can I change the path for pkgconfig without configure file?

**Comment by Cyan4973** [comment]
use `PREFIX` variable : 

`make install PREFIX=/path/to/local/usr/`

**Comment by asdfljdasflkjwfd** [comment]
Thanks problem solved.
