### ISSUE TITLE
LZ4F_decompress seek back in file error

### ISSUE THREAD

**Issue by fpilote** [Cyan4973/lz4#189]
Hi guys, i'm using lz4frame to decompress a file but i'm having problems to seek back in the file to uncompress previously uncompressed data.

In my case, i can't keep all the uncompress data because i'm trying to use less memory as possible but i need to be able to come back to any part of the uncompressed data (using the compressed file).

Simplified example of what i am doing : 
read and decompress byte 0 to byte 2000. 
"do some stuff with uncompressed data"
read and decompress byte 2000 to byte 4000. (previous uncompressed data is overwritten)
"do some stuff with uncompressed data"
read and decompress byte 4000 to byte 6000. (previous uncompressed data is overwritten)
"do some stuff with uncompressed data"
seek back to byte 2000
read and decompress byte 2000 to byte 4000. (previous uncompressed data is overwritten)
LZ4F_decompress returns a "generic error"

Two questions :
- Is it even possible to do this?
- If it is, what am i doing wrong?

I even tried seeking at the beginning of the compressed file (instead of seeking to the known position) but i get the same result.

Thanks for your help guys.

**Comment by Cyan4973** [comment]
> - Is it even possible to do this?

Not with lz4frame, which is designed for streaming (hence serial).

> - If it is, what am i doing wrong?

You'll need to create your own seekable format.
Typically, compress all blocks independently (using regular lz4 compression), and have a table which tells at which position starts which block.

No you can retrieve and decompress any block any time.

You could be inspired by @carlomedas, which created such a format for hadoop : https://github.com/carlomedas/4mc

Note though that compressing small blocks independently will likely have an impact on final compression ratio.

**Comment by fpilote** [comment]
All right, thanks for the quick answer! I'll look into it.
