### ISSUE TITLE
Improve Documentaion

### ISSUE THREAD

**Issue by Vishnu-Hacks** [Cyan4973/lz4#190]
Please improve the documentation, by including a better explanation of working of the compressor and the decompressor. We are a group of students and all are beginners to the open source. It's very hard to understand the working of the code, with the existing documentations. The Readme files only tell about the block/frame format and some information about certain files. A documentation of actual working of the compressor or decompressor would be greatly helpful for beginners like us.  I really appreciate all the contributors for your excellent work.  

Thank You!

**Comment by Cyan4973** [comment]
The point of a format specification is to allow any kind of implementation to exist, and still remain compatible with each other.
Which is a good thing : different environment come with different restrictions and strengths. So a single algorithm wouldn't fit them all.

If you understand the format, then you can create your own program to read it.
I would encourage you to try it.
You will get better insight, and as a result get a better chance to understand the reference source code.
