### ISSUE TITLE
fuzzer found an issue

### ISSUE THREAD

**Issue by setharnold** [Cyan4973/lz4#203]
Hello, a recent Ubuntu build of the lz4 package revealed some issues thanks to the build-time fuzzer run:

https://launchpadlibrarian.net/254045753/buildlog_ubuntu-xenial-s390x.lz4_0.0~r131-2_BUILDING.txt.gz

I got different errors when I compiled with -fsanitize=address and ran the fuzzer on that seed:

sarnold@sec-xenial-amd64:~/lz4-0.0~r131/programs$ ./fuzzer -s6270
Starting LZ4 fuzzer (64-bits, r131)
Seed = 6270
31968   =================================================================
==8767==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fa6ec64f7ff at pc 0x000000431153 bp 0x7ffd85cffa40 sp 0x7ffd85cffa30
WRITE of size 1 at 0x7fa6ec64f7ff thread T0
    #0 0x431152 in FUZ_test (/home/sarnold/lz4-0.0~r131/programs/fuzzer+0x431152)
    #1 0x436ef9 in main (/home/sarnold/lz4-0.0~r131/programs/fuzzer+0x436ef9)
    #2 0x7fa6eb1ee82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #3 0x401278 in _start (/home/sarnold/lz4-0.0~r131/programs/fuzzer+0x401278)

0x7fa6ec64f7ff is located 1 bytes to the left of 163840-byte region [0x7fa6ec64f800,0x7fa6ec677800)
allocated by thread T0 here:
    #0 0x7fa6eb62f54a in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9854a)
    #1 0x43035e in FUZ_test (/home/sarnold/lz4-0.0~r131/programs/fuzzer+0x43035e)
    #2 0x436ef9 in main (/home/sarnold/lz4-0.0~r131/programs/fuzzer+0x436ef9)
    #3 0x7fa6eb1ee82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 FUZ_test
Shadow bytes around the buggy address:
  0x0ff55d8c1ea0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff55d8c1eb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff55d8c1ec0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff55d8c1ed0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ff55d8c1ee0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0ff55d8c1ef0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0ff55d8c1f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff55d8c1f10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff55d8c1f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff55d8c1f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff55d8c1f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==8767==ABORTING

Thanks

**Comment by Cyan4973** [comment]
Thanks for the report @setharnold .

I confirm the bug, which can be faithfully reproduced.
This is an error in the `fuzzer` program itself.
It is now fixed in latest update of "dev" branch

Thanks again, and Best Regards

**Comment by lilianmoraru** [comment]
This can be closed, no?

**Comment by Cyan4973** [comment]
yes
