### ISSUE TITLE
lz4 -h help screen shows wrong version

### ISSUE THREAD

**Issue by nrgiii** [Cyan4973/lz4#206]
lz4 -h shows version r128 even though I'm using r131:

normg@bunk>lz4 -h
*** LZ4 command line interface 64-bits r128, by Yann Collet (Apr 25 2016) ***
Usage :
      lz4 [arg] [input] [output]

input   : a filename
          with no FILE, or when FILE is - or stdin, read standard input
Arguments :
 -1     : Fast compression (default)
 -9     : High compression
 -d     : decompression (default for .lz4 extension)
 -z     : force compression
 -f     : overwrite output without prompting
 -h/-H  : display help/long help and exit

Advanced arguments :
 -V     : display Version number and exit
 -v     : verbose mode
 -q     : suppress warnings; specify twice to suppress errors too
 -c     : force write to standard output, even if it is the console
 -t     : test compressed file integrity
 -m     : multiple input files (implies automatic output filenames)
 -l     : compress using Legacy format (Linux kernel compression)
 -B#    : Block size [4-7](default : 7)
 -BD    : Block dependency (improve compression ratio)
--no-frame-crc : disable stream checksum (default:enabled)
--content-size : compressed frame includes original size (default:not present)
--[no-]sparse  : sparse mode (default:enabled on file, disabled on stdout)
Benchmark arguments :
 -b     : benchmark file(s)
 -i#    : iteration loops [1-9](default : 3), benchmark mode only

**Comment by Cyan4973** [comment]
You probably compiled `lz4` outside of the main `Makefile`, which sets the `VERSION` macro.

This behavior will be changed in a future release.
The plan is to have a version string defined directly within `lz4.h`.
This way, versions will be the same for all packaged binaries, and whatever the build system.

**Comment by ido** [comment]
@Cyan4973  LZ4_VERSION is unset for me when using the main Makefile...I think this is an issue with the Makefile not setting LZ4_VERSION properly.

**Comment by Cyan4973** [comment]
That's unexpected, because reading the `Makefile`, it seems to be set : 

`Makefile` : 
```
# Version number
export VERSION=131
export RELEASE=r$(VERSION)
```

`programs/Makefile` :
```
RELEASE?= r131
CFLAGS += -DLZ4_VERSION=\"$(RELEASE)\"
```

That being said, the solution will be to no longer depend on Makefile to set the version.
The fix will be part of next release.

**Comment by ido** [comment]
Try with "make -e" (which most packagers use) to replicate the problem.

**Comment by ido** [comment]
I think in general you should revamp the build system (maybe switch to CMake officially? Or use zproject to generate CMake+autotools simultaneously?)...but that is just my opinion after reading the various Makefiles throughout the project (some of which have conflicting versions hardcoded in them, even if those versions are overridden by the main Makefile - except when using `-e`)

**Comment by Cyan4973** [comment]
The build system will be revamped to be more in line with [zstd](https://github.com/facebook/zstd)'s one,
where there is a single point of decision for all versions (this will be `lz4.h`).

**Comment by Cyan4973** [comment]
latest `dev` branch update
makes the version number derive entirely from `lz4.h`

**Comment by Cyan4973** [comment]
Fixed in `dev` branch
