### ISSUE TITLE
Data not compressed efficiently 

### ISSUE THREAD

**Issue by Kherbala** [Cyan4973/lz4#215]
Hi !
I am working on tools that need a very fast compression library. So I find Lz4 which make me very happy.
Currently, I am using the low API : LZ4_compress_fast.

When generating some test case, I found a sequence of bytes that makes the Lz4 compression inefficient.

This sequence of bytes is generated with this C++ code (which writes data on stdout) :
cout.flush();
fflush(stdout);
_setmode(_fileno(stdout), _O_BINARY);
for (uint64_t i = 0; i < 0x100000; i++)
{
	cout.write((char *) &i, 4); // write the 32 bits integer
}

When I compressed this data with Lz4 utility, I have this result : 
Compressed 4194304 bytes into 4194323 bytes ==> 100.00%

Is it normal that this sequence of bytes is not compressed efficiently ? Do I make a mistake ?

Thanks !

**Comment by Cyan4973** [comment]
It is expected.

LZ4 has a single heuristic to work with : find exact repetition of _at least_ __4__ bytes (which is where the 4 comes from). In this example, there are none.
Try `cout.write(&i, sizeof(i));`, it will work better.

Such kind of data would benefit from a pre-filter : typically, in this case, it would know that all fields are 4-bytes long, that they are strictly increasing, that the increase between each value is 4, that the convention is little endian, etc.

This is of course specific. Such filter work fine only on some predefined kind of data.

**Comment by Kherbala** [comment]
Hi !
Thanks for your answer !
I know that my real data will be well compressed as expected. But I was a little surprised when I use this type of sequence for my test cases.
