### ISSUE TITLE
MSVC - An internal error has occurred in the compiler

### ISSUE THREAD

**Issue by nbozhinov** [Cyan4973/lz4#220]
Hi,
I am using LZ4 in the form of a static library in the project I am working on.
When compiled with the default optimization settings for the project **Maximize Speed (/O2)** and **Whole program optimization (/GL)** using Visual Studio 2015 update 2 I get "Fatal Error C1001 - An internal error has occurred in the compiler" pointing to the **LZ4F_compressFrame** function.
Without optimization there is no error.
It is not that much of an issue for my project, but I hope you can fix this.
Thanks in advance

**Comment by t-mat** [comment]
@nbozhinov, unfortunately since we have absolutely no information about VC++2015 Update2's internal structure, we can't fix it.  You should report it to Microsoft Visual C++ team via [Connect](https://connect.microsoft.com/visualstudio).

**Comment by Cyan4973** [comment]
@t-mat answer is probably the best we can provide.

I tried to reproduce your issue, using a local copy of Visual Studio 2015 update 2, and compiling lz4 library with mentioned parameters. No problem so far, everything compiles fine.

**Comment by nbozhinov** [comment]
@Cyan4973 @t-mat Thank you for the fast response.

@Cyan4973 I have no problems compiling the lz4 library itself. The problem occurs when using the LZ4F_compressFrame function from another project, with static linking to lz4. I've checked for mismatched vs project settings and there are none.
Reducing the optimization settings solves the problem and doing that is not a big issue for my project, so I will go that way.
Unfortunately I can not provide you with sample code right now as it is part of proprietary project, but I will ask my manager for permissions.
If you consider  this to be bug of VC++2015 Update2 (sounds likely) then this issue may be closed.

Thanks again for spending your time on this.

**Comment by Cyan4973** [comment]
I suspect an optimization bug, likely related to "Whole program optimization (/GL)" .
But indeed it can also be a compiler's bug.

It could be an interesting topic to dig in.
But to do so, we will need an example code able to generate the problem.

**Comment by nbozhinov** [comment]
Yes, playing with the optimization options proved that it is exactly the "Whole program optimization (/GL)" that causes the problem.
I will see if i can extract a minimized version of our code in which the problem occurs, but removing most of the code that is strictly confidential will most likely affect the optimization, so it may be impossible for me to reproduce the problem in a code that I can share.

I am closing the issue as switching off the "Whole program optimization (/GL)" solved the problem.
Thanks for the help.
