### ISSUE TITLE
A bug in frametest

### ISSUE THREAD

**Issue by inikep** [Cyan4973/lz4#232]
`d:\GitHub\lz4\programs>frametest -s9469 -t111080`
Starting lz4frame tester (64-bits, r132)
Seed = 9469
111080   Error at pos 8/334721 : 95 != AF
Error => Decompression failed (error -18:ERROR_contentChecksum_invalid) (seed 9469, test nb 111086)

Tested with `dev` branch.

**Comment by Cyan4973** [comment]
Indeed.
It fails at test 111086, but only if it starts at test 111085 or sooner.
This is potentially an issue with the re-usability of `lz4frame` contexts.
To be investigated ...

**Comment by Cyan4973** [comment]
Fixed by @inikep
