### ISSUE TITLE
ftime

### ISSUE THREAD

**Issue by 0-wiz-0** [Cyan4973/lz4#48]
frametest.c and fuzzer.c need to be adapted in the same way that fullbench and bench already are wrt. sys/timeb.h and the ftime syscall.

Currently, they fail to build e.g. on NetBSD with:
````
# gmake frametest
cc      -I../lib  -O3 -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wstrict-prototypes -pedantic -DLZ4_VERSION=\"r126\"  ../lib/lz4frame.c ../lib/lz4.c ../lib/lz4hc.c ../lib/xxhash.c frametest.c -o frametest
/var/tmp//ccDdJ0OZ.o: In function `fuzzerTests':
frametest.c:(.text+0x1152): undefined reference to `ftime'
frametest.c:(.text+0x13e4): undefined reference to `ftime'
/var/tmp//ccDdJ0OZ.o: In function `main':
frametest.c:(.text.startup+0x2a5): undefined reference to `ftime'
Makefile:90: recipe for target 'frametest' failed
gmake: *** [frametest] Error 1
# gmake fuzzer
cc      -I../lib  -O3 -std=c99 -Wall -Wextra -Wundef -Wshadow -Wcast-align -Wstrict-prototypes -pedantic -DLZ4_VERSION=\"r126\"  ../lib/lz4.c ../lib/lz4hc.c ../lib/xxhash.c fuzzer.c -o fuzzer
/var/tmp//ccMMIjtu.o: In function `FUZ_test':
fuzzer.c:(.text+0x539): undefined reference to `ftime'
fuzzer.c:(.text+0x585): undefined reference to `ftime'
/var/tmp//ccMMIjtu.o: In function `FUZ_unitTests':
fuzzer.c:(.text+0x2d4e): undefined reference to `ftime'
fuzzer.c:(.text+0x2d93): undefined reference to `ftime'
/var/tmp//ccMMIjtu.o: In function `main':
fuzzer.c:(.text.startup+0x3bc): undefined reference to `ftime'
Makefile:84: recipe for target 'fuzzer' failed
gmake: *** [fuzzer] Error 1
````

**Comment by Cyan4973** [comment]
ok, thanks for notification

**Comment by Cyan4973** [comment]
I'm wondering if there is a way to test that.
I can certainly do the requested modification,
but would feel safer if it can be tested automatically,
rather than wait for 3rd party to notify when/if it breaks.

**Comment by 0-wiz-0** [comment]
Well, the usual way is to write configure tests.
I suggest using gettimeofday instead of ftime, it's more portable; or possibly clock_gettime, if you prefer.

**Comment by Cyan4973** [comment]
The dev branch has been updated with requested modifications.
It should compile and run correctly on NetBSD (although I have no NetBSD configuration available around to test).

Regarding the test, it's a bit more complex than that : 
gettimeofday is already tested correctly, using Ubuntu & Mint systems.
What I meant is, I need to test if the fallback to ftime works correctly (including the automated switch itself).
This is system-oriented test, and seems more complex to setup within a C.I. environment.

**Comment by 0-wiz-0** [comment]
Thanks, I tried the dev branch on NetBSD and it built fine.
