### ISSUE TITLE
r128 : lz4io.c could not compile with MSVC

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/lz4#68]
When I compiled r128's programs/lz4io.c with MSVC, I got the following error :

```
1>..\..\programs\lz4io.c(239): warning C4013: 'S_ISREG' undefined; assuming extern returning int
1>lz4io.obj : error LNK2001: unresolved external symbol _S_ISREG
```

Since MSVC does not have `S_ISREG`, we should define equivalent macro. [An answer on StackOverflow](http://stackoverflow.com/a/22404853/2132223) suggests [Curl's macro](https://github.com/bagder/curl/blob/709cf76f6bb7dbaca14e3e8df160ccfac04dcecb/lib/curl_setup.h#L700)

```C
#if !defined(S_ISREG) && defined(S_IFMT) && defined(S_IFREG)
#define S_ISREG(m) (((m) & S_IFMT) == S_IFREG)
#endif
```

Perhaps, it is good time to consider some Windows based online CI environment which has MSVC, eg. [AppVeyor](http://www.appveyor.com/docs/installed-software).

**Comment by Cyan4973** [comment]
Thanks Takayuki

Indeed, this one completely evaded test period.
This is indeed a very strong case for CI environment using MSVC.

I'm a bit surprised, I did not remember having removed this macro. Could be a lapse.

**Comment by t-mat** [comment]
I confirmed 8437a0e43aa5086ec2c23591909e118a85c3d8dd. 0 error/warning.

**Comment by Cyan4973** [comment]
Thanks Takayuki

I also opened an account on AppVeyor, following your recommendation, and I must say that I'm impressed.
I did nothing special, just references the LZ4 repository,
and it nonetheless automatically found the Visual solution, and proceeded to compile it.

https://ci.appveyor.com/project/YannCollet/lz4/build/1.0.2

Great result for such a minimal effort.

**Comment by Cyan4973** [comment]
Merged into master.
Many thanks for the prompt notice !

**Comment by bozaro** [comment]
You can add AppVeyor badge: https://ci.appveyor.com/project/YannCollet/lz4/settings/badges

**Comment by Cyan4973** [comment]
Thanks for the notification Artem. It's a good idea !
