### ISSUE TITLE
Introduce more strict `LZ4F` prefix

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/lz4#90]
Recently, we introduce new function naming convention.  So I think it's good time to change other names.

I would like to add `LZ4F_` prefix to the following names

```
// lz4frame.h
typedef enum { LZ4F_default=0, max64KB=4, max256KB=5, max1MB=6, max4MB=7 } blockSizeID_t;
//                             ^^^^^^^    ^^^^^^^^    ^^^^^^    ^^^^^^     ^^^^^^^^^^^^^

typedef enum { blockLinked=0, blockIndependent} blockMode_t;
//             ^^^^^^^^^^^    ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^

typedef enum { noContentChecksum=0, contentChecksumEnabled } contentChecksum_t;
//             ^^^^^^^^^^^^^^^^^    ^^^^^^^^^^^^^^^^^^^^^^   ^^^^^^^^^^^^^^^^^

typedef enum { LZ4F_frame=0, skippableFrame } frameType_t;
//                           ^^^^^^^^^^^^^^   ^^^^^^^^^^^

// lz4frame_static.h
#define LZ4F_GENERATE_ENUM(ENUM) ENUM,
//                               ^^^^
```

Since replacing these enums will cause source code incompatibility, mark old enums as "obsolete" and append new one.

```
// New
typedef enum { LZ4F_blockLinked=0, LZ4F_blockIndependent } LZ4F_blockMode_t;

// Obsolete
typedef enum { blockLinked=0, blockIndependent} blockMode_t;
```

We also could introduce "deprecated enum" as the following notation

```
enum {
    en_a,
    en_b __attribute__((deprecated)), // gcc, clang
//  en_c __declspec(deprecated),      // MSVC does not allow this form
    en_d __pragma(deprecated(en_b)),  // MSVC (2010 or later)
};
```
 - [Clang : Attributs on enumerators](http://clang.llvm.org/docs/LanguageExtensions.html#attributes-on-enumerators)

but I think it should be another issue in near future.

**Comment by Cyan4973** [comment]
OK, sounds fair.

An important issue is to preserving compatibility with existing code,
but you propose a solution for it too, so it should be okay.

**Comment by t-mat** [comment]
I've pushed [experimental commit](https://github.com/t-mat/lz4/commit/0f7bfff5111a61f29546ff58926cafbafaf52a99) to [my topic branch](https://github.com/t-mat/lz4/tree/issue/90).

Since it overlapped with PR #89 and changes many lines, I don't rush to send this commit as my PR.

**Comment by Cyan4973** [comment]
Commit #95
